name: Release final version

on:
  workflow_dispatch:
    inputs:
      srlinux_version:
        description: 'srlinux release (vYY.M.A)'
        required: true
        type: string
      commit_sha:
        description: 'Commit SHA'
        required: true
        type: string
jobs:
  build:
    name: Final Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout local repo
        uses: actions/checkout@v3
        with:
          ref: generated
          path: work/

      - name: tag major and minor versions
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git tag -a ${{ inputs.srlinux_version }} ${{ inputs.commit_sha }} -m "Release ${{ inputs.srlinux_version }}"
          git push origin ${{ inputs.srlinux_version }} 
        working-directory: work

